### ISSUE TITLE
Install fails on M1 macs

### ISSUE THREAD

**Issue by tessadgreen** [scverse/pertpy#201]
**Describe the bug**

Unable to install using pip on M1 mac (Tessa and @stefanpeidli) 
**To Reproduce**

`mamba create -n pertpy_env python=3.9
conda activate pertpy_env
pip install pertpy`

`(pertpy_env) stefanpeidli@Stefans-MBP ~ % pip install pertpy
Collecting pertpy
  Using cached pertpy-0.3.0-py3-none-any.whl (82 kB)
Collecting muon>=0.1.2
  Using cached muon-0.1.2-py3-none-any.whl (287 kB)
Collecting pypi-latest>=0.1.1
  Using cached pypi_latest-0.1.2-py3-none-any.whl (10 kB)
Collecting scipy<2.0.0,>=1.9.3
  Downloading scipy-1.10.0-cp39-cp39-macosx_12_0_arm64.whl (28.9 MB)`
 `    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ `28.9/28.9 MB 12.3 MB/s eta 0:00:00
Collecting PyYAML>=5.4.1
  Downloading PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 
174.0/174.0 kB 8.3 MB/s eta 0:00:00
Collecting arviz<0.15.0,>=0.14.0
  Using cached arviz-0.14.0-py3-none-any.whl (1.7 MB)
Collecting ipywidgets>=7.6.5
  Downloading ipywidgets-8.0.4-py3-none-any.whl (137 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.8/137.8 kB 8.5 MB/s eta 0:00:00
Collecting scanpy>=1.8.1
  Downloading scanpy-1.9.1-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ `2.0/2.0 MB 12.1 MB/s eta 0:00:00
Collecting pyqt5<6.0.0,>=5.15.7
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error`
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/stefanpeidli/miniconda3/envs/pertpy_env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/stefanpeidli/miniconda3/envs/pertpy_env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/stefanpeidli/miniconda3/envs/pertpy_env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/stefanpeidli/miniconda3/envs/pertpy_env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/fr/z238tpm931s466144gcdpdj40000gn/T/pip-build-env-hvo51gpt/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/fr/z238tpm931s466144gcdpdj40000gn/T/pip-build-env-hvo51gpt/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/fr/z238tpm931s466144gcdpdj40000gn/T/pip-build-env-hvo51gpt/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 585, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/fr/z238tpm931s466144gcdpdj40000gn/T/pip-build-env-hvo51gpt/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/fr/z238tpm931s466144gcdpdj40000gn/T/pip-build-env-hvo51gpt/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/fr/z238tpm931s466144gcdpdj40000gn/T/pip-build-env-hvo51gpt/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
  
`  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Expected behavior**

Installs and loads 

**System [please complete the following information]:**

-   OS: Mac OS Ventura 13.01  [Tessa had the same problem in 13.02] 
-   Language Version: Python 3.9 [Tessa had same in python 3.10] 
-   Virtual environment: miniconda (stefan), miniforge (tessa) 

**Additional context**

brew install of Qt5 seems like it might be necessary, but we're still having trouble with it freezing on the license step for pyqt5 install even after that

**Comment by Zethson** [comment]
@xinyuejohn you're using a M1 right? Got any idea?

**Comment by tessadgreen** [comment]
Prior to installing pertpy, install Qt5 via brew (and follow the directions to add to path), restart terminal, then run:
`pip install pyqt5 --config-settings --confirm-license= --verbose`

Then pip install scanpy works

**Comment by stefanpeidli** [comment]
Note: `conda install -c anaconda pyqt` will lead to a version below the one required by pertpy (5.5.12 < 5.5.17).

**Comment by tessadgreen** [comment]
Accidentally closed when trying to add additional issue:

Setting up developer environment as described [here](https://pertpy.readthedocs.io/en/latest/contributing.html)

At the `make install` step I get 

` • Installing pyqt5-qt5 (5.15.2): Failed

  RuntimeError

  Unable to find installation candidates for pyqt5-qt5 (5.15.2)
`

Installing pyqt5 separately as described above does not fix. 

`make install
rm -fr build/
rm -fr dist/
rm -fr .eggs/
find . -name '*.egg-info' -exec rm -fr {} +
find . -name '*.egg' -exec rm -f {} +
find . -name '*.pyc' -exec rm -f {} +
find . -name '*.pyo' -exec rm -f {} +
find . -name '*~' -exec rm -f {} +
find . -name '__pycache__' -exec rm -fr {} +
poetry install
Installing dependencies from lock file

Package operations: 51 installs, 0 updates, 0 removals

  • Installing pyqt5-qt5 (5.15.2): Failed

  RuntimeError

  Unable to find installation candidates for pyqt5-qt5 (5.15.2)

  at ~/miniforge3/envs/pertpy-distances/lib/python3.9/site-packages/poetry/installation/chooser.py:105 in choose_for
      101│
      102│             links.append(link)
      103│
      104│         if not links:
    → 105│             raise RuntimeError(f"Unable to find installation candidates for {package}")
      106│
      107│         # Get the best link
      108│         chosen = max(links, key=lambda link: self._sort_key(package, link))
      109│

make: *** [install] Error 1`

**Comment by tessadgreen** [comment]
`pip install PyQt5-Qt5
ERROR: Could not find a version that satisfies the requirement PyQt5-Qt5 (from versions: none)
ERROR: No matching distribution found for PyQt5-Qt5`

Not sure where to go from here @Zethson -- we considered removing the requirement from our branch but we're not sure where it's coming from in the first place

**Comment by Zethson** [comment]
It's from ipykernel I think

**Comment by xinyuejohn** [comment]
> @xinyuejohn you're using a M1 right? Got any idea?

Sorry for the late reply. I am using Mac with intel i5.

**Comment by Moomboh** [comment]
The problematic `pyqt5` dependency is required by `ete3`, see https://github.com/etetoolkit/ete/blob/master/setup.py#L81
It is required by `pertpy` [here](https://github.com/theislab/pertpy/blob/development/pyproject.toml#L37), probably because ete3 depends on it. I believe for `ipykernel` it is just an optional dependency.

**Comment by Zethson** [comment]
@Moomboh Indeed. ete3 requires it for plotting. So I'll need to make these dependencies optional urgh.

**Comment by Zethson** [comment]
If I did things correctly, ete3 and pyqt5 should now be optional dependencies. @tessadgreen can you please test the latest development branch?

**Comment by Zethson** [comment]
Apparently people are working on it https://github.com/etetoolkit/ete/issues/656

**Comment by tessadgreen** [comment]
Installing from the latest development branch following the directions in the Contributor Guide works, and I'm seeing the 'ete3' warning on import. Nox runs successfully and I'm able to import pertpy into python. 

Should note that the Qt5 brew install was system wide so it is available in the new environment for me/I don't know if it now works without that step.

**Comment by Zethson** [comment]
@Moomboh thank you very much for your in depth response.

Yes, please open a separate issue for this. I'd also be happy to get a PR in with your suggested improvement and we can discuss it directly there!

**Comment by tessadgreen** [comment]
New brew install required by the _dialogue.py. The new linear programming solver requires system-wise ipopt install on Mac, which can be done with `brew install ipopt`

**Comment by Zethson** [comment]
> New brew install required by the _dialogue.py. The new linear programming solver requires system-wise ipopt install on Mac, which can be done with `brew install ipopt`

It should only be required if you try to run DIALOGUE though, right?

Also, `ipopt` is on conda

**Comment by tessadgreen** [comment]
Oh, yes sorry this came up when trying to run Dialogue, the install was fine/didn't error and I just had the problem when I tried to run the multifactor PMD with the linear programming addition. I got the error `ApplicationError: No executable found for solver 'ipopt'` and followed the directions [here](https://stackoverflow.com/questions/64912995/applicationerror-no-executable-found-for-solver-ipopt-in-pyomo). Assumed that was the problem I was having but I'm going back through the log now and it looks like ipopt isn't a dependency/wasn't installed by pip and the brew was overkill. Sorry for the confusion!

**Comment by Zethson** [comment]
Yeah, I'll write up proper installation instructions soon, sorry.

**Comment by tessadgreen** [comment]
Update: we're failing on M3 mac now, even when following the directions in the documentation to the letter.

`brew install --cask mambaforge`

Run the command as directed by brew to add to your path
(At top of directions) 

`brew install gcc`


https://scipy.github.io/devdocs/building/index.html#system-level-dependencies
Follow the directions here 
 
`brew install gfortran openblas pkg-config`

Run whatever brew tells you to run 
`export LDFLAGS="-L/opt/homebrew/opt/openblas/lib"`
`export CPPFLAGS="-I/opt/homebrew/opt/openblas/include"`


`brew info openblas | grep PKG_CONFIG_PATH`

and then run the command that spits out. 

Create a new environment using mamba (here with python 3.11) and activate it [note: current docs have conflicting python version numbers]
```
mamba create -n pertpy-env python=3.11
mamba activate pertpy-env


git clone https://github.com/scverse/pertpy.git
pip install . 
```

That works, and pytorch is successfully interfacing with MPS (yay)

To make pertpy loadable, then need to run

`pip install arviz toytree formulaic pydeseq2  `

And then we're able to import, though I do get the following warning.

`OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.`

**Comment by tessadgreen** [comment]
update: although this installs and runs, Jax is in CPU-only mode. Trying to figure out if that's fixable via some combination of [this](https://forums.developer.apple.com/forums/thread/731465) and the[ actual directions](https://developer.apple.com/metal/jax/)

**Comment by mschilli87** [comment]
I have a few questions that relate to this issue.
Please point me to the proper place to ask them if this is not it.

1. What (minimum!) version of PyQt is actually required and why?
  * The installation documentation mentions `pyqt5`: https://github.com/scverse/pertpy/blob/33961274183cdadad75175b39633c4186f5f3fdf/docs/installation.md?plain=1#L21
  * `tools/__init__.py` mentiones `pyqt6`, but commented out as 'technically': https://github.com/scverse/pertpy/blob/33961274183cdadad75175b39633c4186f5f3fdf/pertpy/tools/__init__.py#L44 What does that mean?
  * `pyproject.toml` requires `pyqt6`: https://github.com/scverse/pertpy/blob/33961274183cdadad75175b39633c4186f5f3fdf/pyproject.toml#L76
2. Would you be open to split support for scCODA and support for tascCODA when it comes to packaging, such that `pip install 'pertpy[tcoda]'` pulls in `pyqt` but `pip install 'pertpy[coda]'` does not?

I would really like to be able to `conda install pertpy` and while I would like that to include tascCODA support eventuall, getting it with scCODA support only but now would be a huge step forward. Unfortunately, [`conda-forge` does not (yet) support PyQt 6](https://github.com/conda-forge/pyqt-feedstock/issues/124), so based on the current `pyproject.toml`, `pertpy` could only be added without (even) scCONDA support.

The same advantage would apply to Apple silicone installs, if I understand this issue correctly.

**Comment by Zethson** [comment]
@mschilli87 

1. This is fixed in a big doc refactor that I'll probably merge today. It's pyqt6 and ete4 now.
2. Yes, I think this makes sense. I'll have a look later.

While I think it's easier if I tackle this one, generally PRs are very welcome.

**Comment by Zethson** [comment]
@mschilli87 investigated this a bit. Of the Coda extras, only `arviz` is required for scCODA. All other are only required for tascCODA. Have you observed any issues installing `arviz` on MacOS? If not, I will make it a default dependency and rename the extra dependency group.

**Comment by mschilli87** [comment]
@Zethson: Thank you for the fast follow up. I'll check tomorrow and will report back.

**Comment by mschilli87** [comment]
```
Successfully installed arviz-0.21.0
```

Regardless, is arviz even really required to run scCODA or just for (optional) visualization of the MCMC diagnostics?

**Comment by Zethson** [comment]
It's only required for the `summary_prepare` function which is also used for `set_fdr`. There's probably a way to make things less arviz dependent but I would need to spend some time on it which I currently don't have.

**Comment by mschilli87** [comment]
I think if we can get rid of the PyQt dependency alone for scCODA, both M1 Mac and conda installs should be possible already. Adding tascCODA support would be another step for later but I'd be willing to support on that front, given time allows.
Thank you for all the information. Looking forward to the upcoming release. ❤

**Comment by mschilli87** [comment]
Just fyi: I hope to fix this 'soon' via https://github.com/scverse/pertpy/issues/294.

**Comment by Zethson** [comment]
We have a conda-forge package now and the dependencies got leaner. I hope that I can close this for good now. Please complain if not, folks!
