### ISSUE TITLE
Import fail due to missing optional dependencies

### ISSUE THREAD

**Issue by andr-kun** [scverse/pertpy#645]
### Report

I am noticing that pertpy will fail to import due to missing dependencies which is meant to be optional. I have tested this on a clean install (in a new virtual environment) and after installing pertpy (without any optional dependencies), I get the following error when importing pertpy:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 3
      1 import matplotlib
      2 import matplotlib.pyplot as plt
----> 3 import pertpy as pt
      4 import scanpy as sc
      6 plt.rcParams["figure.figsize"] = (7, 7)

File ~/Repositories/pertpy/pertpy/__init__.py:21
     19 from . import plot as pl
     20 from . import preprocessing as pp
---> 21 from . import tools as tl

File ~/Repositories/pertpy/pertpy/tools/__init__.py:3
      1 from pertpy.tools._augur import Augur
      2 from pertpy.tools._cinemaot import Cinemaot
----> 3 from pertpy.tools._coda._sccoda import Sccoda
      4 from pertpy.tools._coda._tasccoda import Tasccoda
      5 from pertpy.tools._dialogue import Dialogue

File ~/Repositories/pertpy/pertpy/tools/_coda/_sccoda.py:5
      1 from __future__ import annotations
      3 from typing import TYPE_CHECKING, Literal
----> 5 import arviz as az
      6 import jax.numpy as jnp
      7 import numpy as np

ModuleNotFoundError: No module named 'arviz'
```

Given that the coda (and de) modules are meant to be optional install, the pertpy package should not be failing to import if the dependencies for the coda (and de) modules are missing.

### Version information

```
-----
matplotlib          3.9.2
pydev_jupyter_utils NA
pydev_jupyter_vars  NA
session_info        1.0.0
-----
IPython             8.26.0
jupyter_client      8.6.2
jupyter_core        5.7.2
jupyterlab          4.2.4
notebook            7.2.1
-----
Python 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]
macOS-14.6.1-arm64-arm-64bit
-----
Session information updated at 2024-08-22 15:34
```

**Comment by Zethson** [comment]
Hey,

which version of pertpy are you using?

**Comment by Zethson** [comment]
@Lilly-May can you test on Mac, please?

@andr-kun our CI tests Linux where this is certainly not an issue. Let's see what we can find...

**Comment by andr-kun** [comment]
I believe that your CI tests by default install all optional dependencies, not just the 'base' pertpy. 

https://github.com/scverse/pertpy/blob/c4233dd19a76ad43900e1b92c073722d300ee58d/.github/workflows/test.yml#L63

This would explain why the CI always passes.

I have tested installing base pertpy in a linux environment (using bioconductor/bioconductor_docker:RELEASE_3_16 docker image as base), and I find the exact same issue:
```
[singularity-build andrian]$ singularity exec pertpy.sif python3
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pertpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pertpy/__init__.py", line 21, in <module>
    from . import tools as tl
  File "/usr/local/lib/python3.10/dist-packages/pertpy/tools/__init__.py", line 3, in <module>
    from pertpy.tools._coda._sccoda import Sccoda
  File "/usr/local/lib/python3.10/dist-packages/pertpy/tools/_coda/_sccoda.py", line 5, in <module>
    import arviz as az
ModuleNotFoundError: No module named 'arviz'
>>> import session_info
>>> session_info.show(html=False)
-----
session_info        1.0.0
-----
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Linux-4.18.0-425.13.1.el8_7.x86_64-x86_64-with-glibc2.35
-----
Session information updated at 2024-08-22 15:57
```

**Comment by Zethson** [comment]
Ouch, reproduced. I'll look into it now!
