### ISSUE TITLE
[sccoda] JAX array with PRNGKey dtype cannot be converted to a NumPy array

### ISSUE THREAD

**Issue by radutanasa** [scverse/pertpy#689]
### Report

Running cell compositional analysis using sccoda fails with:

```
Error
Traceback (most recent call last):
  File "test_cell_composition.py", line 48, in test_cell_composition_obs_with_dot
    output = cell_composition_command.execute(self.adata)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/exec/scrnaseq/cell_composition.py", line 119, in execute
    sccoda_model.run_nuts(sccoda_data, modality_key="coda", rng_key=0)
  File "/.../python3.12/site-packages/pertpy/tools/_coda/_sccoda.py", line 440, in run_nuts
    return super().run_nuts(data, modality_key, num_samples, num_warmup, rng_key, copy, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.12/site-packages/pertpy/tools/_coda/_base_coda.py", line 311, in run_nuts
    sample_adata.uns["scCODA_params"]["mcmc"]["rng_key"] = np.array(rng_key_array)
                                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.12/site-packages/jax/_src/prng.py", line 283, in __array__
    raise TypeError("JAX array with PRNGKey dtype cannot be converted to a NumPy array."
TypeError: JAX array with PRNGKey dtype cannot be converted to a NumPy array. Use jax.random.key_data(arr) if you wish to extract the underlying integer array.
```

The fix should be pretty straighforward:

```
rng_key_data = jax.random.key_data(rng_key_array)
sample_adata.uns["scCODA_params"]["mcmc"]["rng_key"] = np.array(rng_key_data)
```

### Version information

[packages.txt](https://github.com/user-attachments/files/18157059/packages.txt)

**Comment by Zethson** [comment]
Dear @radutanasa 

this is fixed on the main branch. I'll make a release soon. Please try it out.

**Comment by radutanasa** [comment]
Thank you!
